// Pure, dialect-aware DDL generator. No DOM/Electron dependency so it can be
// unit-tested directly. Every builder returns a list of statements (string[])
// because some changes (e.g. Postgres column modify) need multiple statements,
// and the engine's policy gate blocks ";"-joined multi-statements — so callers
// execute each statement separately.

// MySQL support targets MySQL 8.0+ (the app's connectors already assume 8.0).
// Statements like RENAME COLUMN / RENAME TO are not available on MySQL 5.7.
export type Driver = 'mysql' | 'postgres';

export interface ColumnSpec {
  name: string;
  type: string;
  nullable: boolean;
  defaultValue?: string; // raw SQL value as typed (e.g. "'active'", "0"); omit or set to '' for no default
}

// Quote an identifier for the driver, escaping the closing quote char.
export function quoteIdent(driver: Driver, name: string): string {
  if (driver === 'postgres') return '"' + name.replace(/"/g, '""') + '"';
  return '`' + name.replace(/`/g, '``') + '`';
}

function columnTypeClause(col: ColumnSpec): string {
  let s = col.type.trim();
  if (!col.nullable) s += ' NOT NULL';
  if (col.defaultValue && col.defaultValue.trim() !== '') s += ' DEFAULT ' + col.defaultValue.trim();
  return s;
}

export function buildAddColumn(driver: Driver, table: string, col: ColumnSpec): string[] {
  const t = quoteIdent(driver, table);
  const c = quoteIdent(driver, col.name);
  return [`ALTER TABLE ${t} ADD COLUMN ${c} ${columnTypeClause(col)}`];
}

export function buildDropColumn(driver: Driver, table: string, columnName: string): string[] {
  return [`ALTER TABLE ${quoteIdent(driver, table)} DROP COLUMN ${quoteIdent(driver, columnName)}`];
}

export function buildRenameColumn(driver: Driver, table: string, oldName: string, newName: string): string[] {
  const t = quoteIdent(driver, table);
  return [`ALTER TABLE ${t} RENAME COLUMN ${quoteIdent(driver, oldName)} TO ${quoteIdent(driver, newName)}`];
}

function sameDefault(a?: string, b?: string): boolean {
  return (a ?? '').trim() === (b ?? '').trim();
}

// Modify a column's type/nullability/default. `before` and `after` share the
// same column name (renames go through buildRenameColumn). Returns [] if there
// is no effective change.
export function buildModifyColumn(driver: Driver, table: string, before: ColumnSpec, after: ColumnSpec): string[] {
  const t = quoteIdent(driver, table);
  const c = quoteIdent(driver, before.name);

  const typeChanged = before.type.trim() !== after.type.trim();
  const nullChanged = before.nullable !== after.nullable;
  const defChanged = !sameDefault(before.defaultValue, after.defaultValue);
  if (!typeChanged && !nullChanged && !defChanged) return [];

  if (driver === 'mysql') {
    // MySQL MODIFY must restate the whole definition.
    return [`ALTER TABLE ${t} MODIFY COLUMN ${c} ${columnTypeClause(after)}`];
  }

  // Postgres: one statement per changed attribute.
  const out: string[] = [];
  if (typeChanged) out.push(`ALTER TABLE ${t} ALTER COLUMN ${c} TYPE ${after.type.trim()}`);
  if (nullChanged) {
    out.push(`ALTER TABLE ${t} ALTER COLUMN ${c} ${after.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`);
  }
  if (defChanged) {
    const def = after.defaultValue?.trim() ?? '';
    const hasDef = def !== '';
    out.push(
      `ALTER TABLE ${t} ALTER COLUMN ${c} ${hasDef ? 'SET DEFAULT ' + def : 'DROP DEFAULT'}`
    );
  }
  return out;
}

export function buildDropTable(driver: Driver, table: string): string[] {
  return [`DROP TABLE ${quoteIdent(driver, table)}`];
}

// ALTER ... RENAME TO works on both MySQL 8 and PostgreSQL.
export function buildRenameTable(driver: Driver, table: string, newName: string): string[] {
  return [`ALTER TABLE ${quoteIdent(driver, table)} RENAME TO ${quoteIdent(driver, newName)}`];
}

export interface CreateColumnSpec {
  name: string;
  type: string;
  nullable: boolean;
  defaultValue?: string;
  primaryKey?: boolean;
  autoIncrement?: boolean;
  unique?: boolean;
}

// Build a CREATE TABLE statement. PK columns are forced NOT NULL; auto-increment
// uses AUTO_INCREMENT (MySQL) or GENERATED BY DEFAULT AS IDENTITY (Postgres) and
// gets no DEFAULT; any PK columns are collected into a table-level PRIMARY KEY.
export function buildCreateTable(driver: Driver, table: string, columns: CreateColumnSpec[]): string[] {
  const cols = columns.filter((c) => c.name.trim() && c.type.trim());
  if (cols.length === 0) return [];
  const q = (n: string) => quoteIdent(driver, n);

  const lines = cols.map((c) => {
    const notNull = !!c.primaryKey || !c.nullable;
    let s = `${q(c.name)} ${c.type.trim()}`;
    if (notNull) s += ' NOT NULL';
    if (c.autoIncrement) s += driver === 'mysql' ? ' AUTO_INCREMENT' : ' GENERATED BY DEFAULT AS IDENTITY';
    if (c.unique) s += ' UNIQUE';
    if (!c.autoIncrement && c.defaultValue && c.defaultValue.trim() !== '') s += ' DEFAULT ' + c.defaultValue.trim();
    return s;
  });

  const pkCols = cols.filter((c) => c.primaryKey).map((c) => q(c.name));
  if (pkCols.length > 0) lines.push(`PRIMARY KEY (${pkCols.join(', ')})`);

  const body = lines.map((l) => '  ' + l).join(',\n');
  return [`CREATE TABLE ${q(table)} (\n${body}\n)`];
}

export function buildTruncateTable(driver: Driver, table: string): string[] {
  return [`TRUNCATE TABLE ${quoteIdent(driver, table)}`];
}

export interface TableChangeSet {
  renameTo?: string; // new table name if changed
  addColumns: ColumnSpec[];
  dropColumns: string[]; // column names
  renameColumns: { from: string; to: string }[];
  modifyColumns: { before: ColumnSpec; after: ColumnSpec }[]; // same-name type/null/default changes
}

// Flatten a form's change set into ordered statements. Column ops run against
// the ORIGINAL table name; the table rename (if any) runs last so every prior
// statement still references the existing table.
export function buildTableChanges(driver: Driver, table: string, changes: TableChangeSet): string[] {
  const out: string[] = [];
  for (const name of changes.dropColumns) out.push(...buildDropColumn(driver, table, name));
  for (const m of changes.modifyColumns) out.push(...buildModifyColumn(driver, table, m.before, m.after));
  for (const r of changes.renameColumns) out.push(...buildRenameColumn(driver, table, r.from, r.to));
  for (const col of changes.addColumns) out.push(...buildAddColumn(driver, table, col));
  if (changes.renameTo && changes.renameTo.trim() !== '' && changes.renameTo.trim() !== table) {
    out.push(...buildRenameTable(driver, table, changes.renameTo.trim()));
  }
  return out;
}
